<?php
pdo_query("CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_account` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`acid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`openid` varchar(50) NOT NULL,
`username` varchar(50) NOT NULL,
`password` varchar(32) NOT NULL,
`salt` varchar(6) NOT NULL,
`mobile` varchar(20) NOT NULL,
`status` tinyint(3) NOT NULL DEFAULT '2',
`store_id` int(10) unsigned NOT NULL DEFAULT '0',
`joindate` int(10) unsigned NOT NULL DEFAULT '0',
`joinip` varchar(15) NOT NULL,
`lastvisit` int(10) unsigned NOT NULL DEFAULT '0',
`lastip` varchar(15) NOT NULL,
`remark` varchar(500) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_activity_bargain` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`content` varchar(255) NOT NULL,
`order_limit` tinyint(3) unsigned NOT NULL DEFAULT '0',
`goods_limit` tinyint(3) unsigned NOT NULL DEFAULT '0',
`starttime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
`starthour` smallint(5) unsigned NOT NULL DEFAULT '0',
`endhour` smallint(5) unsigned NOT NULL DEFAULT '0',
`use_limit` tinyint(3) unsigned NOT NULL DEFAULT '1',
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`status` varchar(20) NOT NULL DEFAULT 'ongoing',
`total_updatetime` int(10) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `agentid` (`agentid`),
KEY `status` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_activity_bargain_goods` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`bargain_id` int(10) unsigned NOT NULL DEFAULT '0',
`goods_id` int(10) unsigned NOT NULL DEFAULT '0',
`discount_price` varchar(10) NOT NULL DEFAULT '0',
`max_buy_limit` tinyint(3) unsigned NOT NULL DEFAULT '1',
`poi_user_type` varchar(10) NOT NULL DEFAULT 'all',
`discount_total` int(10) NOT NULL DEFAULT '-1',
`discount_available_total` int(10) NOT NULL DEFAULT '-1',
`dosage` int(10) unsigned NOT NULL DEFAULT '0',
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`mall_displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `bargain_id` (`bargain_id`),
KEY `goods_id` (`goods_id`),
KEY `status` (`status`),
KEY `mall_displayorder` (`mall_displayorder`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_activity_coupon` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '公号序号',
`sid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '公号序号',
`type` varchar(20) NOT NULL DEFAULT 'collect',
`title` varchar(30) NOT NULL COMMENT '标题',
`discount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '折扣券(折扣率), 代金券(面额)',
`condition` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '订单满多少可用',
`type_limit` int(10) NOT NULL DEFAULT '1' COMMENT '1:所有用户都可领取,2:新用户可领取',
`dosage` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '已领取数量',
`amount` int(10) unsigned NOT NULL COMMENT '总发行数量',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1:可领取,2:暂停领取',
`starttime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '开始时间',
`endtime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '结束时间',
`addtime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '发行时间',
`activity_id` int(10) unsigned NOT NULL DEFAULT '0',
`coupons` varchar(1000) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `type` (`type`),
KEY `starttime` (`starttime`),
KEY `endtime` (`endtime`),
KEY `status` (`status`),
KEY `activity_id` (`activity_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_activity_coupon_grant_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '序号',
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`couponid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL COMMENT '用户编号',
`grant_type` tinyint(3) NOT NULL DEFAULT '1' COMMENT '状态: 1:一次性领取,2:每天领取 ',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `couponid` (`couponid`),
KEY `uid` (`uid`),
KEY `addtime` (`addtime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_activity_coupon_record` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '序号',
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`couponid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL COMMENT '用户编号',
`order_id` int(10) unsigned NOT NULL DEFAULT '0',
`code` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) NOT NULL DEFAULT '1' COMMENT '状态: 1:未使用,2:已使用 ',
`remark` varchar(300) NOT NULL,
`granttime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '发放时间',
`usetime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '使用时间',
`type` varchar(20) NOT NULL DEFAULT 'couponCollect',
`discount` int(10) unsigned NOT NULL DEFAULT '0',
`condition` int(10) unsigned NOT NULL DEFAULT '0',
`starttime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
`channel` varchar(30) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `couponid` (`couponid`),
KEY `uid` (`uid`),
KEY `status` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_activity_redpacket_record` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(50) NOT NULL,
`activity_id` int(10) unsigned NOT NULL DEFAULT '0',
`channel` varchar(20) NOT NULL,
`uid` int(10) unsigned NOT NULL,
`order_id` int(10) unsigned NOT NULL DEFAULT '0',
`code` int(10) unsigned NOT NULL DEFAULT '0',
`type` varchar(20) NOT NULL,
`discount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`condition` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`starttime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) NOT NULL DEFAULT '1',
`remark` varchar(300) NOT NULL,
`granttime` int(10) unsigned NOT NULL DEFAULT '0',
`usetime` int(10) unsigned NOT NULL DEFAULT '0',
`category_limit` varchar(500) NOT NULL,
`times_limit` varchar(500) NOT NULL,
`is_show` tinyint(3) unsigned NOT NULL DEFAULT '1',
`super_share_id` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `redpacketid` (`activity_id`),
KEY `uid` (`uid`),
KEY `status` (`status`),
KEY `is_show` (`is_show`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_address` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`realname` varchar(15) NOT NULL,
`sex` varchar(10) NOT NULL,
`mobile` varchar(15) NOT NULL,
`name` varchar(255) NOT NULL,
`address` varchar(50) NOT NULL,
`number` varchar(20) NOT NULL,
`location_x` varchar(20) NOT NULL,
`location_y` varchar(20) NOT NULL,
`is_default` tinyint(3) unsigned NOT NULL DEFAULT '0',
`type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1:收货地址, 2:服务地址',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`mode` varchar(20) NOT NULL DEFAULT 'favorite',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_agent` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL,
`title` varchar(50) NOT NULL,
`realname` varchar(50) NOT NULL,
`mobile` varchar(20) NOT NULL,
`area` varchar(30) NOT NULL,
`initial` varchar(10) NOT NULL,
`salt` varchar(10) NOT NULL,
`password` varchar(32) NOT NULL,
`status` tinyint(3) unsigned,
`sysset` text NOT NULL,
`pluginset` text NOT NULL,
`account` varchar(1000) NOT NULL,
`amount` decimal(10,2) NOT NULL,
`fee` varchar(5000) NOT NULL,
`geofence` text NOT NULL,
`data` text NOT NULL,
`displayorder` int(10) unsigned NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `status` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_agent_current_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL,
`agentid` int(10) unsigned NOT NULL,
`trade_type` tinyint(3) unsigned NOT NULL,
`order_type` varchar(20) NOT NULL,
`extra` varchar(255) NOT NULL,
`fee` decimal(10,2) NOT NULL,
`amount` decimal(10,2) NOT NULL,
`addtime` int(10) unsigned NOT NULL,
`remark` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_agent_getcash_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL,
`agentid` int(10) unsigned NOT NULL,
`trade_no` varchar(20) NOT NULL,
`get_fee` decimal(10,2) NOT NULL,
`take_fee` decimal(10,2) NOT NULL,
`final_fee` decimal(10,2) NOT NULL,
`account` varchar(500) NOT NULL,
`status` tinyint(3) unsigned NOT NULL,
`addtime` int(10) unsigned NOT NULL,
`endtime` int(10) unsigned NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_assign_board` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`queue_id` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`mobile` varchar(15) NOT NULL,
`openid` varchar(64) NOT NULL,
`guest_num` tinyint(3) unsigned NOT NULL DEFAULT '0',
`number` varchar(20) NOT NULL,
`position` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`is_notify` tinyint(3) unsigned NOT NULL DEFAULT '0',
`createtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_assign_queue` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`guest_num` tinyint(3) unsigned NOT NULL DEFAULT '0',
`notify_num` tinyint(3) unsigned NOT NULL DEFAULT '0',
`starttime` varchar(10) NOT NULL,
`endtime` varchar(10) NOT NULL,
`prefix` varchar(10) NOT NULL COMMENT '前缀',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`position` int(10) unsigned NOT NULL DEFAULT '1',
`updatetime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '根据这个时间,判断是否将position重新至0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_cache` (
`name` varchar(50) NOT NULL,
`value` longtext NOT NULL,
PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_category` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`type` varchar(20) NOT NULL DEFAULT 'member',
`alias` varchar(20) NOT NULL,
`title` varchar(30) NOT NULL,
`color` varchar(15) NOT NULL,
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`is_system` tinyint(3) unsigned NOT NULL DEFAULT '0',
`score` tinyint(3) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `type` (`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_clerk` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(15) NOT NULL,
`nickname` varchar(15) NOT NULL,
`openid` varchar(60) NOT NULL,
`mobile` varchar(20) NOT NULL,
`password` varchar(32) NOT NULL,
`salt` varchar(6) NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`avatar` varchar(255) NOT NULL,
`updatetime` int(10) unsigned NOT NULL DEFAULT '0',
`token` varchar(50) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `status` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_config` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sysset` text NOT NULL,
`pluginset` text NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_creditshop_order` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`credits` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`itemcode` int(10) unsigned NOT NULL DEFAULT '0',
`actualprice` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`faceprice` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`description` varchar(255) NOT NULL,
`ordernum` varchar(255) NOT NULL,
`ordersn` varchar(50) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_cube` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`tips` varchar(20) NOT NULL,
`thumb` varchar(255) NOT NULL,
`link` varchar(255) NOT NULL,
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned DEFAULT '0',
`wxapp_link` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_delivery_cards` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`days` int(10) unsigned NOT NULL DEFAULT '0',
`price` int(10) unsigned NOT NULL DEFAULT '0',
`day_free_limit` tinyint(3) unsigned NOT NULL DEFAULT '2',
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_delivery_cards_order` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`acid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`openid` varchar(60) NOT NULL,
`ordersn` varchar(20) NOT NULL,
`card_id` int(10) unsigned NOT NULL DEFAULT '0',
`final_fee` varchar(20) NOT NULL,
`pay_type` varchar(20) NOT NULL,
`is_pay` tinyint(3) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`paytime` int(10) unsigned NOT NULL DEFAULT '0',
`starttime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_delivery_config` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`mobile_verify_status` tinyint(3) unsigned NOT NULL DEFAULT '2',
`agreement` text NOT NULL,
`delivery_type` tinyint(3) unsigned NOT NULL DEFAULT '1',
`plateform_delivery_fee` tinyint(3) unsigned NOT NULL DEFAULT '0',
`delivery_fee_type` tinyint(3) unsigned NOT NULL DEFAULT '1',
`delivery_fee` varchar(10) NOT NULL,
`get_cash_fee_limit` int(10) unsigned NOT NULL DEFAULT '0',
`get_cash_fee_rate` varchar(10) NOT NULL,
`get_cash_fee_min` int(10) unsigned NOT NULL DEFAULT '0',
`get_cash_fee_max` int(10) unsigned NOT NULL DEFAULT '0',
`card_apply_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`card_agreement` text NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_deliveryer` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(15) NOT NULL,
`nickname` varchar(15) NOT NULL,
`openid` varchar(60) NOT NULL,
`avatar` varchar(255) NOT NULL,
`mobile` varchar(15) NOT NULL,
`password` varchar(32) NOT NULL,
`salt` varchar(6) NOT NULL,
`token` varchar(32) NOT NULL,
`sex` varchar(5) NOT NULL,
`age` tinyint(3) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`credit1` decimal(10,2) NOT NULL DEFAULT '0.00',
`credit2` decimal(10,2) NOT NULL DEFAULT '0.00',
`work_status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`location_x` varchar(20) NOT NULL,
`location_y` varchar(20) NOT NULL,
`order_takeout_num` tinyint(3) unsigned NOT NULL DEFAULT '0',
`order_errander_num` tinyint(3) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`auth_info` varchar(500) NOT NULL,
`groupid` int(10) unsigned NOT NULL DEFAULT '0',
`is_takeout` tinyint(3) NOT NULL DEFAULT '0',
`is_errander` tinyint(3) NOT NULL DEFAULT '0',
`extra` varchar(500) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`),
KEY `work_status` (`work_status`),
KEY `token` (`token`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_deliveryer_current_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`deliveryer_id` int(10) unsigned NOT NULL DEFAULT '0',
`order_type` varchar(20) NOT NULL DEFAULT 'order',
`trade_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1:订单入账, 2: 申请提现',
`extra` varchar(255) NOT NULL,
`fee` decimal(10,2) NOT NULL DEFAULT '0.00',
`amount` decimal(10,2) NOT NULL DEFAULT '0.00',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`remark` varchar(255) NOT NULL,
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `deliveryer_id` (`deliveryer_id`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`),
KEY `trade_type` (`trade_type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_deliveryer_getcash_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`deliveryer_id` int(10) unsigned NOT NULL DEFAULT '0',
`trade_no` varchar(20) NOT NULL,
`get_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`take_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`final_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`status` tinyint(3) unsigned NOT NULL DEFAULT '2' COMMENT '1:申请成功,2:申请中',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
`account` varchar(1000) NOT NULL,
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `deliveryer_id` (`deliveryer_id`),
KEY `agentid` (`agentid`),
KEY `status` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_deliveryer_groups` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`uniacid` int(11) NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`group_condition` int(10) unsigned NOT NULL DEFAULT '0',
`delivery_fee` varchar(2000) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_deliveryer_location_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`deliveryer_id` int(10) unsigned NOT NULL DEFAULT '0',
`location_x` varchar(20) NOT NULL,
`location_y` varchar(20) NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`addtime_cn` varchar(50) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `deliveryer_id` (`deliveryer_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_deliveryer_transfer_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`deliveryer_id` int(10) unsigned NOT NULL DEFAULT '0',
`order_type` varchar(20) NOT NULL DEFAULT 'takeout',
`order_id` int(10) unsigned NOT NULL DEFAULT '0',
`reason` varchar(20) NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`stat_year` smallint(10) unsigned NOT NULL DEFAULT '0',
`stat_month` int(10) unsigned NOT NULL DEFAULT '0',
`stat_day` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `deliveryer_id` (`deliveryer_id`),
KEY `stat_year` (`stat_year`),
KEY `stat_month` (`stat_month`),
KEY `stat_day` (`stat_day`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_diypage` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`type` tinyint(3) unsigned NOT NULL DEFAULT '0',
`name` varchar(255) NOT NULL,
`data` longtext NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`updatetime` int(10) unsigned NOT NULL DEFAULT '0',
`diymenu` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `type` (`type`),
KEY `addtime` (`addtime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_diypage_menu` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) NOT NULL DEFAULT '0',
`name` varchar(255) NOT NULL,
`data` text NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`updatetime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `addtime` (`addtime`),
KEY `updatetime` (`updatetime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_diypage_template` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`type` tinyint(3) unsigned NOT NULL DEFAULT '0',
`name` varchar(255) NOT NULL,
`data` longtext NOT NULL,
`preview` varchar(255) NOT NULL,
`code` varchar(50) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `type` (`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_errander_category` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`thumb` varchar(255) NOT NULL,
`type` varchar(20) NOT NULL DEFAULT 'buy',
`label` varchar(1000) NOT NULL,
`start_fee` varchar(10) NOT NULL,
`start_km` varchar(10) NOT NULL,
`pre_km_fee` varchar(10) NOT NULL DEFAULT '0',
`tip_min` varchar(10) NOT NULL DEFAULT '0',
`tip_max` varchar(10) NOT NULL DEFAULT '0',
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`rule` text NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`goods_thumbs_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`is_on_upload` tinyint(3) unsigned NOT NULL DEFAULT '0',
`delivery_within_days` tinyint(3) unsigned NOT NULL DEFAULT '0',
`delivery_times` text NOT NULL,
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`pre_km` varchar(10) NOT NULL DEFAULT '1',
`weight_fee_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`weight_fee` text NOT NULL,
`multiaddress` varchar(500) NOT NULL,
`group_discount` varchar(1000) NOT NULL,
`labels` varchar(1000) NOT NULL,
`notice` varchar(500) NOT NULL,
`deliveryers` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`),
KEY `status` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_errander_order` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`acid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`openid` varchar(50) NOT NULL,
`code` varchar(10) NOT NULL,
`order_sn` varchar(20) NOT NULL,
`order_type` varchar(20) NOT NULL DEFAULT 'buy',
`order_cid` int(10) unsigned NOT NULL DEFAULT '0',
`goods_name` varchar(60) NOT NULL,
`goods_price` varchar(30) NOT NULL,
`goods_weight` varchar(10) NOT NULL,
`buy_username` varchar(20) NOT NULL,
`buy_sex` varchar(5) NOT NULL,
`buy_mobile` varchar(15) NOT NULL,
`buy_address` varchar(100) NOT NULL,
`buy_location_x` varchar(20) NOT NULL,
`buy_location_y` varchar(20) NOT NULL,
`accept_username` varchar(20) NOT NULL,
`accept_sex` varchar(5) NOT NULL,
`accept_mobile` varchar(15) NOT NULL,
`accept_address` varchar(100) NOT NULL,
`accept_location_x` varchar(20) NOT NULL,
`accept_location_y` varchar(20) NOT NULL,
`distance` varchar(20) NOT NULL,
`delivery_time` varchar(30) NOT NULL,
`pay_type` varchar(15) NOT NULL,
`is_pay` tinyint(3) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`paytime` int(10) unsigned NOT NULL DEFAULT '0',
`delivery_status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`deliveryer_id` int(10) unsigned NOT NULL DEFAULT '0',
`delivery_assign_time` int(10) unsigned NOT NULL DEFAULT '0',
`delivery_instore_time` int(10) unsigned NOT NULL DEFAULT '0',
`delivery_success_time` int(10) unsigned NOT NULL DEFAULT '0',
`delivery_success_location_x` varchar(15) NOT NULL,
`delivery_success_location_y` varchar(15) NOT NULL,
`status` tinyint(3) NOT NULL DEFAULT '1',
`print_nums` tinyint(3) unsigned NOT NULL DEFAULT '0',
`delivery_fee` varchar(10) NOT NULL,
`delivery_tips` varchar(10) NOT NULL,
`total_fee` varchar(10) NOT NULL,
`discount_fee` varchar(20) NOT NULL DEFAULT '0.00',
`final_fee` varchar(20) NOT NULL DEFAULT '0.00',
`deliveryer_fee` varchar(10) NOT NULL,
`deliveryer_total_fee` varchar(10) NOT NULL DEFAULT '0',
`note` varchar(200) NOT NULL,
`is_remind` tinyint(3) unsigned NOT NULL DEFAULT '0',
`is_anonymous` tinyint(3) unsigned NOT NULL DEFAULT '0',
`anonymous_username` varchar(15) NOT NULL,
`out_trade_no` varchar(50) NOT NULL,
`refund_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`refund_out_no` varchar(40) NOT NULL,
`refund_apply_time` int(10) unsigned NOT NULL DEFAULT '0',
`refund_success_time` int(10) unsigned NOT NULL DEFAULT '0',
`refund_channel` varchar(30) NOT NULL,
`refund_account` varchar(30) NOT NULL,
`delivery_handle_type` varchar(15) NOT NULL DEFAULT 'wechat',
`order_channel` varchar(20) NOT NULL DEFAULT 'wap',
`stat_year` int(10) unsigned NOT NULL DEFAULT '0',
`stat_month` int(10) unsigned NOT NULL DEFAULT '0',
`stat_day` int(10) unsigned NOT NULL DEFAULT '0',
`thumbs` varchar(1000) NOT NULL,
`transaction_id` varchar(60) NOT NULL,
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`agent_discount_fee` varchar(10) NOT NULL DEFAULT '0.00',
`agent_serve_fee` varchar(10) NOT NULL DEFAULT '0.00',
`agent_serve` varchar(1000) NOT NULL,
`agent_final_fee` varchar(10) NOT NULL DEFAULT '0.00',
`plateform_serve_fee` varchar(10) NOT NULL DEFAULT '0.00',
`plateform_serve` varchar(1000) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`),
KEY `addtime` (`addtime`),
KEY `paytime` (`paytime`),
KEY `is_pay` (`is_pay`),
KEY `pay_type` (`pay_type`),
KEY `refund_status` (`refund_status`),
KEY `delivery_status` (`delivery_status`),
KEY `status` (`status`),
KEY `deliveryer_id` (`deliveryer_id`),
KEY `stat_year` (`stat_year`),
KEY `stat_month` (`stat_month`),
KEY `stat_day` (`stat_day`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_errander_order_status_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`oid` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`type` varchar(20) NOT NULL,
`title` varchar(30) NOT NULL,
`note` varchar(255) NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `oid` (`oid`),
KEY `status` (`status`),
KEY `type` (`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_fans` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`openid` varchar(50) NOT NULL,
`nickname` varchar(30) NOT NULL,
`sex` varchar(3) NOT NULL,
`avatar` varchar(255) NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_freelunch` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(50) NOT NULL,
`thumb` varchar(100) NOT NULL,
`max_partake_times` int(10) unsigned NOT NULL DEFAULT '0',
`partake_grant_type` tinyint(3) unsigned NOT NULL DEFAULT '0',
`reward_grant_type` tinyint(3) unsigned NOT NULL DEFAULT '1',
`redpacket_days_limit` tinyint(3) unsigned NOT NULL DEFAULT '0',
`pre_partaker_num` int(10) unsigned NOT NULL DEFAULT '0',
`pre_partaker_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`pre_reward_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`plus_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`plus_thumb` varchar(255) NOT NULL,
`plus_partaker_num` int(10) unsigned NOT NULL DEFAULT '0',
`plus_reward_num` int(10) unsigned NOT NULL DEFAULT '1',
`plus_pre_partaker_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`pre_plus_reward_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`serial_sn` int(10) unsigned NOT NULL DEFAULT '1',
`plus_serial_sn` int(10) unsigned NOT NULL DEFAULT '1',
`share` varchar(3000) NOT NULL,
`agreement` text NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`starttime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
`pre_max_partake_times` int(10) unsigned NOT NULL DEFAULT '0',
`plus_pre_max_partake_times` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `starttime` (`starttime`),
KEY `endtime` (`endtime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_freelunch_partaker` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`freelunch_id` int(10) unsigned NOT NULL DEFAULT '0',
`record_id` int(10) unsigned NOT NULL DEFAULT '0',
`serial_sn` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`number` int(10) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`final_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`order_sn` varchar(50) NOT NULL,
`is_pay` tinyint(3) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `freelunch_id` (`freelunch_id`),
KEY `record_id` (`record_id`),
KEY `uid` (`uid`),
KEY `serial_sn` (`serial_sn`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_freelunch_record` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`freelunch_id` int(10) unsigned NOT NULL DEFAULT '0',
`serial_sn` int(10) unsigned NOT NULL DEFAULT '1',
`type` varchar(20) NOT NULL DEFAULT 'common',
`partaker_total` int(10) unsigned NOT NULL DEFAULT '0',
`partaker_dosage` int(10) unsigned NOT NULL DEFAULT '0',
`partaker_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`reward_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`reward_uid` varchar(1000) NOT NULL,
`reward_number` int(10) unsigned NOT NULL DEFAULT '0',
`startime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `freelunch_id` (`freelunch_id`),
KEY `serial_sn` (`serial_sn`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_goods` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`cid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(30) NOT NULL,
`price` varchar(500) NOT NULL,
`discount_price` varchar(500) NOT NULL,
`box_price` varchar(10) NOT NULL DEFAULT '0',
`min_buy_limit` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '最少购买数量',
`is_options` tinyint(3) unsigned NOT NULL DEFAULT '0',
`unitname` varchar(10) NOT NULL DEFAULT '份',
`total` int(10) NOT NULL DEFAULT '0',
`sailed` int(10) unsigned NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`is_hot` tinyint(3) unsigned NOT NULL DEFAULT '0',
`thumb` varchar(255) NOT NULL,
`slides` varchar(1000) NOT NULL,
`label` varchar(5) NOT NULL,
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`description` text NOT NULL,
`comment_total` int(10) unsigned NOT NULL DEFAULT '0',
`comment_good` int(10) unsigned NOT NULL DEFAULT '0',
`print_label` int(10) unsigned NOT NULL DEFAULT '0',
`total_update_type` tinyint(3) unsigned NOT NULL DEFAULT '1',
`content` varchar(100) NOT NULL,
`number` varchar(50) NOT NULL,
`attrs` varchar(1000) NOT NULL,
`old_price` varchar(10) NOT NULL,
`elemeId` varchar(50) NOT NULL DEFAULT '0',
`meituanId` varchar(50) NOT NULL DEFAULT '0',
`openplateformCode` varchar(50) NOT NULL DEFAULT '0',
`total_warning` int(10) unsigned NOT NULL DEFAULT '0',
`child_id` int(20) unsigned NOT NULL DEFAULT '0',
`is_showtime` tinyint(3) NOT NULL DEFAULT '0',
`start_time1` varchar(10) NOT NULL,
`end_time1` varchar(10) NOT NULL,
`start_time2` varchar(10) NOT NULL,
`end_time2` varchar(10) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `cid` (`cid`),
KEY `title` (`title`),
KEY `is_hot` (`is_hot`),
KEY `status` (`status`),
KEY `displayorder` (`displayorder`),
KEY `elemeId` (`elemeId`),
KEY `meituanId` (`meituanId`),
KEY `openplateformCode` (`openplateformCode`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_goods_category` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`min_fee` int(10) unsigned NOT NULL DEFAULT '0',
`elemeId` varchar(50) NOT NULL DEFAULT '0',
`parentid` int(10) NOT NULL DEFAULT '0',
`description` varchar(100) NOT NULL,
`is_showtime` tinyint(3) NOT NULL DEFAULT '0',
`start_time` varchar(10) NOT NULL,
`end_time` varchar(10) NOT NULL,
`week` varchar(50) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `status` (`status`),
KEY `displayorder` (`displayorder`),
KEY `elemeId` (`elemeId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_goods_options` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`goods_id` int(10) unsigned NOT NULL DEFAULT '0',
`name` varchar(50) NOT NULL,
`price` varchar(50) NOT NULL,
`total` int(10) NOT NULL DEFAULT '-1',
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`total_warning` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `goods_id` (`goods_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_help` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(100) NOT NULL,
`content` mediumtext NOT NULL,
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`click` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `title` (`title`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_member_footmark` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`stat_day` int(10) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`),
KEY `sid` (`sid`),
KEY `stat_day` (`stat_day`),
KEY `agentid` (`agentid`),
KEY `addtime` (`addtime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_member_groups` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`uniacid` int(11) NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`group_condition` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_member_invoice` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(255) NOT NULL,
`recognition` varchar(50) NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`),
KEY `addtime` (`addtime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_member_recharge` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL,
`uid` int(10) unsigned NOT NULL,
`openid` varchar(50) NOT NULL,
`order_sn` varchar(40) NOT NULL,
`fee` varchar(10) NOT NULL,
`final_fee` decimal(10,2) NOT NULL DEFAULT '0.00',
`type` varchar(15) NOT NULL DEFAULT 'credit',
`tag` varchar(1000) NOT NULL,
`is_pay` tinyint(1) NOT NULL DEFAULT '0',
`pay_type` varchar(20) NOT NULL,
`addtime` int(10) unsigned NOT NULL,
`paytime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_members` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`openid` varchar(50) NOT NULL,
`avatar` varchar(255) NOT NULL,
`nickname` varchar(50) NOT NULL,
`sex` varchar(5) NOT NULL,
`realname` varchar(20) NOT NULL,
`mobile` varchar(20) NOT NULL,
`setmeal_id` int(10) unsigned NOT NULL DEFAULT '0',
`setmeal_day_free_limit` tinyint(3) unsigned NOT NULL DEFAULT '0',
`setmeal_starttime` int(10) unsigned NOT NULL DEFAULT '0',
`setmeal_endtime` int(10) unsigned NOT NULL DEFAULT '0',
`first_order_time` int(10) unsigned NOT NULL DEFAULT '0',
`last_order_time` int(10) unsigned NOT NULL DEFAULT '0',
`success_num` int(10) unsigned DEFAULT '0',
`success_price` decimal(10,2) NOT NULL DEFAULT '0.00',
`cancel_num` int(10) unsigned NOT NULL DEFAULT '0',
`cancel_price` decimal(10,2) NOT NULL DEFAULT '0.00',
`is_sys` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1:系统会员, 2:模块兼容会员',
`search_data` varchar(255) NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`mobile_audit` tinyint(3) unsigned NOT NULL DEFAULT '0',
`salt` varchar(10) NOT NULL,
`password` varchar(32) NOT NULL,
`openid_qq` varchar(50) NOT NULL,
`openid_wx` varchar(50) NOT NULL,
`register_type` varchar(20) NOT NULL DEFAULT 'wechat',
`success_first_time` int(10) unsigned NOT NULL DEFAULT '0',
`success_last_time` int(10) unsigned NOT NULL DEFAULT '0',
`cancel_first_time` int(10) unsigned NOT NULL DEFAULT '0',
`cancel_last_time` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`credit1` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`credit2` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`token` varchar(50) NOT NULL,
`uid_qianfan` int(10) unsigned NOT NULL DEFAULT '0',
`uid_majia` int(10) unsigned NOT NULL DEFAULT '0',
`is_spread` tinyint(3) unsigned NOT NULL DEFAULT '0',
`spreadcredit2` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`spreadtime` int(10) unsigned NOT NULL DEFAULT '0',
`groupid` int(10) unsigned NOT NULL DEFAULT '0',
`spread1` int(10) unsigned NOT NULL DEFAULT '0',
`spread2` int(10) unsigned NOT NULL DEFAULT '0',
`spread_groupid` int(10) unsigned NOT NULL DEFAULT '0',
`spread_status` int(10) unsigned NOT NULL DEFAULT '0',
`groupid_updatetime` int(10) unsigned NOT NULL DEFAULT '0',
`spreadfixed` tinyint(3) unsigned NOT NULL DEFAULT '0',
`openid_wxapp` varchar(50) NOT NULL,
`unionId` varchar(50) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`),
KEY `cancel_first_time` (`cancel_first_time`),
KEY `cancel_last_time` (`cancel_last_time`),
KEY `success_first_time` (`success_first_time`),
KEY `success_last_time` (`success_last_time`),
KEY `first_order_time` (`success_first_time`),
KEY `last_order_time` (`success_last_time`),
KEY `uid_qianfan` (`uid_qianfan`),
KEY `is_spread` (`is_spread`),
KEY `spreadtime` (`spreadtime`),
KEY `openid` (`openid`),
KEY `uid_majia` (`uid_majia`),
KEY `spread1` (`spread1`),
KEY `spread2` (`spread2`),
KEY `spead_groupid` (`spread_groupid`),
KEY `spead_status` (`spread_status`),
KEY `speadid1` (`spread1`),
KEY `speadid2` (`spread2`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_news` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`cateid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(100) NOT NULL,
`desc` varchar(255) NOT NULL,
`content` mediumtext NOT NULL,
`thumb` varchar(255) NOT NULL,
`author` varchar(50) NOT NULL,
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`is_display` tinyint(3) unsigned NOT NULL DEFAULT '1',
`is_show_home` tinyint(3) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`click` int(10) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `title` (`title`),
KEY `cateid` (`cateid`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_news_category` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(30) NOT NULL,
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`type` varchar(15) NOT NULL,
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `type` (`type`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_notice` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`type` varchar(20) NOT NULL DEFAULT 'member',
`title` varchar(60) NOT NULL,
`link` varchar(255) NOT NULL,
`content` text NOT NULL,
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`thumb` varchar(255) NOT NULL,
`description` text NOT NULL,
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`starttime|583|basic|11.5.0|20180226192032` int(10) unsigned NOT NULL DEFAULT '0',
`wxapp_link` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`),
KEY `status` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_notice_read_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`notice_id` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`is_new` tinyint(3) unsigned NOT NULL DEFAULT '1',
PRIMARY KEY (`id`),
KEY `uid` (`uid`),
KEY `notice_id` (`notice_id`),
KEY `is_new` (`is_new`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_oauth_fans` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`appid` varchar(50) NOT NULL,
`openid` varchar(50) NOT NULL,
`oauth_openid` varchar(50) NOT NULL,
PRIMARY KEY (`id`),
KEY `appid` (`appid`),
KEY `openid` (`openid`),
KEY `oauth_openid` (`oauth_openid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`acid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`groupid` int(10) unsigned NOT NULL DEFAULT '0',
`order_type` tinyint(3) unsigned NOT NULL DEFAULT '1',
`is_pay` tinyint(3) unsigned NOT NULL DEFAULT '0',
`ordersn` varchar(20) NOT NULL,
`code` int(10) unsigned NOT NULL DEFAULT '0',
`openid` varchar(50) NOT NULL,
`username` varchar(20) NOT NULL,
`sex` varchar(5) NOT NULL,
`mobile` varchar(15) NOT NULL,
`address` varchar(100) NOT NULL,
`number` varchar(20) NOT NULL,
`location_x` varchar(20) NOT NULL,
`location_y` varchar(20) NOT NULL,
`note` varchar(200) NOT NULL,
`price` decimal(10,2) NOT NULL,
`num` tinyint(3) unsigned NOT NULL,
`delivery_day` varchar(20) NOT NULL,
`delivery_time` varchar(20) NOT NULL,
`pay_type` varchar(15) NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`paytime` int(10) unsigned NOT NULL DEFAULT '0',
`delivery_assign_time` int(10) NOT NULL DEFAULT '0',
`delivery_success_time` int(10) NOT NULL DEFAULT '0',
`status` tinyint(3) NOT NULL DEFAULT '1',
`delivery_status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '3:待配送, 4:配送中, 5: 配送成功, 6: 配送失败',
`delivery_type` tinyint(3) unsigned NOT NULL DEFAULT '1',
`is_comment` tinyint(3) unsigned NOT NULL DEFAULT '0',
`print_nums` tinyint(3) unsigned NOT NULL DEFAULT '0',
`delivery_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '外卖配送费',
`pack_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`serve_fee` varchar(10) NOT NULL,
`discount_fee` varchar(20) NOT NULL DEFAULT '0.00',
`total_fee` varchar(20) NOT NULL DEFAULT '0.00',
`final_fee` varchar(20) NOT NULL DEFAULT '0.00',
`vip_free_delivery_fee` tinyint(3) unsigned NOT NULL DEFAULT '0',
`invoice` varchar(50) NOT NULL,
`data` text NOT NULL,
`is_remind` tinyint(3) unsigned NOT NULL DEFAULT '0',
`deliveryer_id` int(10) unsigned NOT NULL DEFAULT '0',
`is_refund` tinyint(3) unsigned NOT NULL DEFAULT '0',
`person_num` tinyint(3) unsigned NOT NULL DEFAULT '1',
`table_id` int(10) unsigned NOT NULL DEFAULT '0',
`table_cid` int(10) unsigned NOT NULL DEFAULT '0',
`reserve_type` varchar(10) NOT NULL,
`reserve_time` varchar(30) NOT NULL,
`transaction_id` varchar(60) NOT NULL COMMENT '第三方支付交易号',
`box_price` varchar(10) NOT NULL DEFAULT '0',
`delivery_handle_type` varchar(20) NOT NULL DEFAULT 'wechat',
`delivery_success_location_x` varchar(15) NOT NULL,
`delivery_success_location_y` varchar(15) NOT NULL,
`delivery_instore_time` int(10) NOT NULL DEFAULT '0',
`deliveryingtime` int(10) unsigned NOT NULL DEFAULT '0',
`deliveryinstoretime` int(10) unsigned NOT NULL DEFAULT '0',
`deliveryedtime` int(10) unsigned NOT NULL,
`deliverysuccesstime` int(10) unsigned NOT NULL DEFAULT '0',
`serial_sn` int(10) unsigned NOT NULL DEFAULT '1',
`handletime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
`refund_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`store_final_fee` varchar(10) NOT NULL DEFAULT '0',
`store_discount_fee` varchar(10) NOT NULL DEFAULT '0',
`plateform_discount_fee` varchar(10) NOT NULL DEFAULT '0',
`plateform_serve_rate` varchar(10) NOT NULL DEFAULT '0',
`plateform_serve_fee` varchar(10) NOT NULL DEFAULT '0',
`plateform_delivery_fee` varchar(10) NOT NULL DEFAULT '0',
`plateform_deliveryer_fee` varchar(10) NOT NULL DEFAULT '0',
`refund_fee` varchar(10) NOT NULL DEFAULT '0',
`out_trade_no` varchar(50) NOT NULL,
`stat_year` smallint(10) unsigned NOT NULL DEFAULT '0',
`stat_month` int(10) unsigned NOT NULL DEFAULT '0',
`stat_day` int(10) unsigned NOT NULL DEFAULT '0',
`order_channel` varchar(20) NOT NULL DEFAULT 'wap',
`mall_first_order` tinyint(3) unsigned NOT NULL DEFAULT '0',
`plateform_serve` varchar(500) NOT NULL,
`deductcredit2` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`is_timeout` tinyint(3) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`agent_serve` varchar(500) NOT NULL,
`agent_final_fee` varchar(10) NOT NULL DEFAULT '0',
`agent_serve_fee` varchar(10) NOT NULL DEFAULT '0',
`agent_discount_fee` varchar(10) NOT NULL DEFAULT '0',
`spread1` int(10) unsigned NOT NULL DEFAULT '0',
`spread2` int(10) unsigned NOT NULL DEFAULT '0',
`clerk_notify_collect_time` int(10) NOT NULL DEFAULT '0',
`distance` varchar(20) NOT NULL DEFAULT '0.00',
`last_notify_deliveryer_time` int(10) unsigned NOT NULL DEFAULT '0',
`last_notify_clerk_time` int(10) unsigned NOT NULL DEFAULT '0',
`notify_deliveryer_total` tinyint(3) unsigned NOT NULL DEFAULT '0',
`notify_clerk_total` tinyint(3) unsigned NOT NULL DEFAULT '0',
`elemeOrderId` varchar(60) NOT NULL,
`elemeDowngraded` tinyint(3) unsigned NOT NULL DEFAULT '0',
`eleme_store_final_fee` varchar(10) NOT NULL DEFAULT '0.00',
`order_plateform` varchar(20) NOT NULL DEFAULT 'we7_wmall',
`spreadbalance` tinyint(3) unsigned NOT NULL DEFAULT '0',
`meituanOrderId` varchar(50) NOT NULL DEFAULT '0',
`meituan_store_final_fee` varchar(10) NOT NULL DEFAULT '0.00',
`delivery_takegoods_time` int(10) unsigned NOT NULL DEFAULT '0',
`extra_fee` varchar(20) NOT NULL DEFAULT '0.00',
`is_delete` tinyint(3) NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid_sid` (`uniacid`,`sid`),
KEY `delivery_status` (`delivery_status`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `delivery_type` (`delivery_type`),
KEY `uid` (`uid`),
KEY `order_type` (`order_type`),
KEY `status` (`status`),
KEY `refund_status` (`refund_status`),
KEY `addtime` (`addtime`),
KEY `paytime` (`paytime`),
KEY `endtime` (`endtime`),
KEY `pay_type` (`pay_type`),
KEY `stat_year` (`stat_year`),
KEY `stat_month` (`stat_month`),
KEY `stat_day` (`stat_day`),
KEY `is_pay` (`is_pay`),
KEY `deliveryer_id` (`deliveryer_id`),
KEY `agentid` (`agentid`),
KEY `clerk_notify_collect_time` (`clerk_notify_collect_time`),
KEY `handletime` (`handletime`),
KEY `elemeOrderId` (`elemeOrderId`),
KEY `order_plateform` (`order_plateform`),
KEY `elemeDowngraded` (`elemeDowngraded`),
KEY `spread1` (`spread1`),
KEY `spread2` (`spread2`),
KEY `spreadbalance` (`spreadbalance`),
KEY `meituanOrderId` (`meituanOrderId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_cart` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`groupid` int(10) unsigned NOT NULL DEFAULT '0',
`num` int(10) unsigned NOT NULL DEFAULT '0',
`price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`data` text NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`paytime` int(10) unsigned NOT NULL DEFAULT '0',
`box_price` varchar(10) NOT NULL DEFAULT '0',
`original_price` varchar(10) NOT NULL DEFAULT '0.00',
`original_data` text NOT NULL,
`bargain_use_limit` tinyint(3) unsigned NOT NULL DEFAULT '0',
`num_data` varchar(2000) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `uid` (`uid`),
KEY `uniacid_sid` (`uniacid`,`sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_comment` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`oid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`username` varchar(20) NOT NULL,
`avatar` varchar(255) NOT NULL,
`mobile` varchar(15) NOT NULL,
`goods_quality` tinyint(3) unsigned NOT NULL DEFAULT '0',
`delivery_service` tinyint(3) unsigned NOT NULL DEFAULT '0',
`score` tinyint(3) unsigned NOT NULL DEFAULT '0',
`note` varchar(255) NOT NULL,
`data` varchar(1000) NOT NULL,
`thumbs` varchar(3000) NOT NULL,
`reply` varchar(500) NOT NULL,
`replytime` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`addtime` int(10) NOT NULL DEFAULT '0',
`is_share` tinyint(3) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`deliveryer_id` int(10) unsigned NOT NULL DEFAULT '0',
`taste_score` tinyint(3) unsigned NOT NULL DEFAULT '0',
`package_score` tinyint(3) unsigned NOT NULL DEFAULT '0',
`deliveryer_tag` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `oid` (`oid`),
KEY `addtime` (`addtime`),
KEY `agentid` (`agentid`),
KEY `delivery_service` (`delivery_service`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_current_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`acid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`openid` varchar(50) NOT NULL,
`username` varchar(20) NOT NULL,
`mobile` varchar(20) NOT NULL,
`orderid` int(10) unsigned NOT NULL DEFAULT '0',
`fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`is_pay` tinyint(3) unsigned NOT NULL DEFAULT '0',
`pay_type` varchar(15) NOT NULL,
`order_status` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '订单状态',
`trade_status` tinyint(3) unsigned NOT NULL DEFAULT '2' COMMENT '交易记录1:成功,2:进行中,3:失败,4:交易关闭.',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`remark` varchar(255) NOT NULL,
`out_trade_no` varchar(40) NOT NULL COMMENT '商户支付订单号',
`out_refund_no` varchar(40) NOT NULL COMMENT '商户退款订单号',
`refund_status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '1:申请中, 2:退款中, 3:退款成功, 4:退款失败',
`refund_time` int(10) unsigned NOT NULL DEFAULT '0',
`refund_channel` varchar(20) NOT NULL,
`refund_account` varchar(50) NOT NULL,
`delivery_type` tinyint(3) unsigned NOT NULL DEFAULT '1',
`deliveryer_id` int(10) unsigned NOT NULL DEFAULT '0',
`deliveryer_fee` varchar(10) NOT NULL,
`store_deliveryer_fee` varchar(10) NOT NULL,
`vip_free_delivery_fee` tinyint(3) unsigned NOT NULL DEFAULT '0',
`final_fee` decimal(10,2) NOT NULL DEFAULT '0.00',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_discount` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`oid` int(10) unsigned NOT NULL DEFAULT '0',
`type` varchar(20) NOT NULL,
`name` varchar(20) NOT NULL,
`icon` varchar(20) NOT NULL,
`note` varchar(50) NOT NULL,
`fee` varchar(20) NOT NULL DEFAULT '0.00',
`store_discount_fee` varchar(10) NOT NULL DEFAULT '0',
`plateform_discount_fee` varchar(10) NOT NULL DEFAULT '0',
`agent_discount_fee` varchar(10) NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `oid` (`oid`),
KEY `type` (`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_grant` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`max` int(10) unsigned NOT NULL DEFAULT '0',
`continuous` int(10) unsigned NOT NULL DEFAULT '0',
`sum` int(10) unsigned NOT NULL DEFAULT '0',
`updatetime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`),
KEY `continuous` (`continuous`),
KEY `sum` (`sum`),
KEY `updatetime` (`updatetime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_grant_record` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`oid` int(10) unsigned NOT NULL DEFAULT '0',
`days` int(10) unsigned NOT NULL DEFAULT '0',
`grant` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`credittype` varchar(20) NOT NULL,
`type` tinyint(3) unsigned NOT NULL DEFAULT '0',
`stat_month` int(10) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`mark` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`),
KEY `times` (`days`),
KEY `type` (`type`),
KEY `addtime` (`addtime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_peerpay` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`uniacid` int(11) NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`plid` int(10) unsigned NOT NULL DEFAULT '0',
`orderid` int(11) NOT NULL DEFAULT '0',
`peerpay_type` tinyint(1) NOT NULL DEFAULT '0',
`peerpay_price` decimal(10,2) NOT NULL DEFAULT '0.00',
`peerpay_maxprice` decimal(10,2) NOT NULL DEFAULT '0.00',
`peerpay_realprice` decimal(10,2) NOT NULL DEFAULT '0.00',
`peerpay_selfpay` decimal(10,2) NOT NULL DEFAULT '0.00',
`peerpay_message` varchar(500) NOT NULL,
`status` tinyint(1) NOT NULL DEFAULT '0',
`createtime` int(10) unsigned NOT NULL DEFAULT '0',
`data` varchar(1000) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `orderid` (`orderid`),
KEY `plid` (`plid`),
KEY `uid` (`uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_peerpay_payinfo` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`pid` int(11) NOT NULL DEFAULT '0',
`order_sn` varchar(50) NOT NULL,
`uid` int(11) NOT NULL DEFAULT '0',
`uname` varchar(255) NOT NULL,
`usay` varchar(500) NOT NULL,
`final_fee` decimal(10,2) NOT NULL DEFAULT '0.00',
`createtime` int(11) NOT NULL DEFAULT '0',
`paytime` int(10) unsigned NOT NULL DEFAULT '0',
`headimg` varchar(255),
`refundstatus` tinyint(1) NOT NULL DEFAULT '0',
`refundprice` decimal(10,2) NOT NULL DEFAULT '0.00',
`openid` varchar(255) NOT NULL,
`is_pay` tinyint(3) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `pid` (`pid`),
KEY `openid` (`openid`),
KEY `order_sn` (`order_sn`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_print_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`pid` tinyint(3) unsigned NOT NULL DEFAULT '0',
`oid` int(10) unsigned NOT NULL DEFAULT '0',
`foid` varchar(50) NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '2' COMMENT '1:打印成功,2:打印未成功',
`printer_type` varchar(20) NOT NULL DEFAULT 'feie',
`addtime` int(10) unsigned NOT NULL,
PRIMARY KEY (`id`),
KEY `addtime` (`addtime`),
KEY `foid` (`foid`),
KEY `uniacid` (`uniacid`),
KEY `pid` (`pid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_refund` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`acid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`order_id` int(10) unsigned NOT NULL DEFAULT '0',
`order_sn` varchar(50) NOT NULL,
`reason` varchar(100) NOT NULL,
`pay_type` varchar(15) NOT NULL,
`fee` varchar(10) NOT NULL DEFAULT '0',
`out_trade_no` varchar(60) NOT NULL DEFAULT '0',
`out_refund_no` varchar(50) NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`apply_time` int(10) unsigned NOT NULL DEFAULT '0',
`handle_time` int(10) unsigned NOT NULL DEFAULT '0',
`success_time` int(10) unsigned NOT NULL DEFAULT '0',
`channel` varchar(30) NOT NULL,
`account` varchar(30) NOT NULL,
`order_channel` varchar(20) NOT NULL DEFAULT 'wap',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `order_id` (`order_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_refund_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`order_type` varchar(20) NOT NULL DEFAULT 'order',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`oid` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`type` varchar(20) NOT NULL,
`title` varchar(30) NOT NULL,
`note` varchar(255) NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `oid` (`oid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_remind_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`oid` int(10) unsigned NOT NULL DEFAULT '0',
`remindid` varchar(50) NOT NULL DEFAULT '0',
`channel` varchar(15) NOT NULL DEFAULT 'system',
`status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`reply` varchar(255) NOT NULL,
`addtime` int(10) unsigned NOT NULL,
PRIMARY KEY (`id`),
KEY `addtime` (`addtime`),
KEY `uniacid` (`uniacid`),
KEY `oid` (`oid`),
KEY `remindid` (`remindid`),
KEY `channel` (`channel`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_stat` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`oid` int(10) unsigned NOT NULL DEFAULT '0',
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`goods_id` int(10) unsigned NOT NULL DEFAULT '0',
`goods_cid` int(10) unsigned NOT NULL DEFAULT '0',
`goods_num` int(10) unsigned NOT NULL DEFAULT '0',
`goods_title` varchar(30) NOT NULL,
`goods_unit_price` varchar(10) NOT NULL,
`goods_price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`print_label` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`addtime` int(10) NOT NULL DEFAULT '0',
`goods_category_title` varchar(20) NOT NULL,
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`option_id` int(10) unsigned NOT NULL DEFAULT '0',
`goods_discount_num` int(10) unsigned NOT NULL DEFAULT '0',
`goods_original_price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`bargain_id` int(10) unsigned NOT NULL DEFAULT '0',
`total_update_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`stat_year` smallint(10) unsigned NOT NULL DEFAULT '0',
`stat_month` int(10) unsigned NOT NULL DEFAULT '0',
`stat_week` int(10) unsigned NOT NULL DEFAULT '0',
`stat_day` int(10) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`goods_number` varchar(30) NOT NULL,
`order_plateform` varchar(20) NOT NULL DEFAULT 'we7_wmall',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `addtime` (`addtime`),
KEY `bargain_id` (`bargain_id`),
KEY `uid` (`uid`),
KEY `agentid` (`agentid`),
KEY `oid` (`oid`),
KEY `order_plateform` (`order_plateform`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_order_status_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`oid` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`type` varchar(20) NOT NULL,
`title` varchar(30) NOT NULL,
`note` varchar(255) NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`role` varchar(30) NOT NULL,
`role_cn` varchar(50) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `oid` (`oid`),
KEY `type` (`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_paybill_order` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`acid` int(10) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`openid` varchar(50) NOT NULL,
`serial_sn` int(10) unsigned NOT NULL DEFAULT '0',
`order_sn` varchar(50) NOT NULL,
`pay_type` varchar(15) NOT NULL,
`is_pay` tinyint(3) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`paytime` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) NOT NULL DEFAULT '1',
`total_fee` varchar(10) NOT NULL DEFAULT '0.00',
`no_discount_part` varchar(10) NOT NULL DEFAULT '0.00',
`discount_fee` varchar(20) NOT NULL DEFAULT '0.00',
`final_fee` varchar(20) NOT NULL DEFAULT '0.00',
`plateform_serve_fee` varchar(10) NOT NULL DEFAULT '0.00',
`plateform_serve` varchar(1000) NOT NULL,
`store_final_fee` varchar(10) NOT NULL DEFAULT '0',
`out_trade_no` varchar(50) NOT NULL,
`transaction_id` varchar(60) NOT NULL,
`stat_year` int(10) unsigned NOT NULL DEFAULT '0',
`stat_month` int(10) unsigned NOT NULL DEFAULT '0',
`stat_day` int(10) unsigned NOT NULL DEFAULT '0',
`agent_serve_fee` varchar(10) NOT NULL DEFAULT '0.00',
`agent_serve` varchar(1000) NOT NULL,
`agent_final_fee` varchar(10) DEFAULT '0.00',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`),
KEY `stat_year` (`stat_year`),
KEY `stat_month` (`stat_month`),
KEY `stat_day` (`stat_day`),
KEY `addtime` (`addtime`),
KEY `paytime` (`paytime`),
KEY `is_pay` (`is_pay`),
KEY `pay_type` (`pay_type`),
KEY `status` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_paylog` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`order_sn` varchar(20) NOT NULL,
`order_id` int(10) unsigned NOT NULL DEFAULT '0',
`order_type` varchar(30) NOT NULL,
`fee` varchar(10) NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`paytime` int(10) unsigned NOT NULL DEFAULT '0',
`out_trade_order_id` varchar(50) NOT NULL,
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`data` varchar(1000) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`),
KEY `order_sn` (`order_sn`),
KEY `order_id` (`order_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_perm_account` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`plugins` text,
`max_store` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_perm_role` (
`id` int(10) NOT NULL AUTO_INCREMENT,
`uniacid` int(10) NOT NULL DEFAULT '0',
`rolename` varchar(255) NOT NULL,
`status` tinyint(3) NOT NULL DEFAULT '0',
`perms` text NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_perm_user` (
`id` int(10) NOT NULL AUTO_INCREMENT,
`uniacid` int(10) NOT NULL DEFAULT '0',
`uid` int(10) NOT NULL DEFAULT '0',
`roleid` int(10) NOT NULL DEFAULT '0',
`status` tinyint(3) NOT NULL DEFAULT '0',
`perms` text NOT NULL,
`realname` varchar(255) NOT NULL,
`mobile` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid` (`uid`),
KEY `roleid` (`roleid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_plugin` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`name` varchar(100) NOT NULL,
`type` varchar(20) NOT NULL,
`title` varchar(100) NOT NULL,
`thumb` varchar(255),
`version` varchar(10) NOT NULL,
`ability` varchar(255) NOT NULL,
`status` int(10) DEFAULT '0',
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`is_show` tinyint(3) unsigned NOT NULL DEFAULT '1',
PRIMARY KEY (`id`),
KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_printer` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL,
`name` varchar(20) NOT NULL,
`type` varchar(20) NOT NULL DEFAULT 'feie',
`print_no` varchar(30) NOT NULL,
`member_code` varchar(50) NOT NULL COMMENT '商户编号',
`key` varchar(50) NOT NULL,
`api_key` varchar(100) NOT NULL COMMENT '易联云打印机api_key',
`print_nums` tinyint(3) unsigned NOT NULL DEFAULT '1',
`print_label` varchar(50) NOT NULL,
`is_print_all` tinyint(3) unsigned NOT NULL DEFAULT '1',
`qrcode_link` varchar(100) NOT NULL,
`print_header` varchar(50) NOT NULL,
`print_footer` varchar(50) NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`qrcode_type` varchar(20) NOT NULL DEFAULT 'custom',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_printer_label` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_reply` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`rid` int(10) unsigned NOT NULL DEFAULT '0',
`type` varchar(50),
`table_id` int(10) unsigned NOT NULL DEFAULT '0',
`extra` text NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_report` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`acid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`openid` varchar(50) NOT NULL,
`mobile` varchar(20) NOT NULL,
`title` varchar(255) NOT NULL,
`note` varchar(255) NOT NULL,
`thumbs` varchar(2000) NOT NULL,
`status` tinyint(3) NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_reserve` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`time` varchar(15) NOT NULL,
`table_cid` int(10) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_shareredpacket` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(50) NOT NULL,
`share_redpacket_condition` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`share_redpacket_min` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`share_redpacket_max` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`share_redpacket_days_limit` tinyint(3) unsigned NOT NULL DEFAULT '0',
`follow_redpacket_min` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`follow_redpacket_max` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`follow_redpacket_days_limit` tinyint(3) unsigned NOT NULL DEFAULT '0',
`share` varchar(3000) NOT NULL,
`agreement` text NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`starttime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `status` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_shareredpacket_invite_record` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`activity_id` int(10) unsigned NOT NULL DEFAULT '0',
`share_uid` int(10) unsigned NOT NULL DEFAULT '0',
`follow_uid` int(10) unsigned NOT NULL DEFAULT '0',
`share_redpacket_condition` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`share_redpacket_discount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`share_redpacket_days_limit` tinyint(3) unsigned NOT NULL DEFAULT '0',
`follow_redpacket_condition` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`follow_redpacket_discount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`follow_redpacket_days_limit` tinyint(3) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `activity_id` (`activity_id`),
KEY `share_uid` (`share_uid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_slide` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(30) NOT NULL,
`thumb` varchar(255) NOT NULL,
`link` varchar(255) NOT NULL,
`type` tinyint(3) unsigned NOT NULL DEFAULT '1',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`wxapp_link` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `type` (`type`),
KEY `status` (`status`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_spread_current_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`spreadid` int(10) unsigned NOT NULL DEFAULT '0',
`trade_type` tinyint(3) unsigned NOT NULL DEFAULT '1',
`extra` varchar(255) NOT NULL,
`fee` decimal(10,2) NOT NULL DEFAULT '0.00',
`amount` decimal(10,2) NOT NULL DEFAULT '0.00',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`remark` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
KEY `spreadid` (`spreadid`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_spread_getcash_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`spreadid` int(10) unsigned NOT NULL DEFAULT '0',
`trade_no` varchar(20) NOT NULL,
`get_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`take_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`final_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`channel` varchar(20) NOT NULL DEFAULT 'wechat',
`account` varchar(500) NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '2',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `status` (`status`),
KEY `agentid` (`agentid`),
KEY `spreadid` (`spreadid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_spread_groups` (
`id` int(10) NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`commission1` varchar(20) NOT NULL DEFAULT '0',
`commission2` varchar(20) NOT NULL DEFAULT '0',
`group_condition` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_store` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`cid` varchar(50) NOT NULL,
`title` varchar(30) NOT NULL,
`logo` varchar(100) NOT NULL,
`telephone` varchar(15) NOT NULL,
`business_hours` varchar(200) NOT NULL,
`is_in_business` tinyint(3) unsigned NOT NULL DEFAULT '1',
`description` text NOT NULL,
`send_price` smallint(5) unsigned NOT NULL DEFAULT '0',
`delivery_price` varchar(255) NOT NULL DEFAULT '0',
`delivery_free_price` int(10) unsigned NOT NULL DEFAULT '0',
`pack_price` float(10,2) unsigned NOT NULL DEFAULT '0.00',
`delivery_time` tinyint(3) unsigned NOT NULL DEFAULT '0',
`delivery_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1:商家配送,2:到店自提,3:两种都支持',
`delivery_within_days` tinyint(3) unsigned NOT NULL DEFAULT '0',
`delivery_reserve_days` tinyint(3) unsigned DEFAULT '0',
`serve_radius` varchar(30) NOT NULL DEFAULT '0.00',
`serve_fee` varchar(255) NOT NULL,
`delivery_area` varchar(50) NOT NULL,
`thumbs` varchar(1000) NOT NULL,
`address` varchar(50) NOT NULL,
`location_x` varchar(15) NOT NULL,
`location_y` varchar(15) NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`sns` varchar(255) NOT NULL,
`notice` varchar(100) NOT NULL COMMENT '公告',
`tips` varchar(100) NOT NULL,
`content` varchar(255) NOT NULL,
`payment` varchar(255) NOT NULL,
`invoice_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`token_status` tinyint(3) unsigned DEFAULT '0',
`remind_time_limit` tinyint(3) unsigned NOT NULL DEFAULT '10',
`remind_reply` varchar(1500) NOT NULL,
`comment_reply` varchar(2000) NOT NULL,
`sailed` int(10) unsigned NOT NULL DEFAULT '0',
`score` varchar(10) NOT NULL,
`first_order_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`discount_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`grant_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`bargain_price_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`reserve_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`collect_coupon_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`grant_coupon_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`comment_status` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '评论审核.1:直接通过',
`sms_use_times` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '短信使用条数',
`wechat_qrcode` varchar(500) NOT NULL,
`custom_url` varchar(1000) NOT NULL,
`addtype` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1:后台添加,2:申请入驻',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`template` varchar(20) NOT NULL DEFAULT 'index',
`pc_notice_status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`not_in_serve_radius` tinyint(3) unsigned NOT NULL DEFAULT '1',
`auto_handel_order` tinyint(3) unsigned NOT NULL DEFAULT '0',
`auto_get_address` tinyint(3) unsigned NOT NULL DEFAULT '1',
`auto_notice_deliveryer` tinyint(3) unsigned NOT NULL DEFAULT '0',
`click` int(10) unsigned NOT NULL DEFAULT '0',
`is_recommend` tinyint(3) unsigned NOT NULL DEFAULT '0',
`is_assign` tinyint(3) unsigned NOT NULL DEFAULT '0',
`is_reserve` tinyint(3) unsigned NOT NULL DEFAULT '0',
`is_meal` tinyint(3) unsigned NOT NULL DEFAULT '0',
`forward_mode` varchar(15) NOT NULL,
`assign_mode` tinyint(3) unsigned NOT NULL DEFAULT '1',
`assign_qrcode` varchar(255) NOT NULL,
`delivery_mode` tinyint(3) unsigned NOT NULL DEFAULT '1',
`order_note` varchar(255) NOT NULL COMMENT '订单备注',
`forward_url` varchar(100) NOT NULL,
`delivery_fee_mode` tinyint(3) unsigned NOT NULL DEFAULT '1',
`delivery_times` varchar(10000) NOT NULL,
`qualification` varchar(1000) NOT NULL,
`label` int(10) NOT NULL DEFAULT '0',
`delivery_areas` text NOT NULL,
`push_token` varchar(50) NOT NULL,
`is_rest` tinyint(3) unsigned NOT NULL DEFAULT '0',
`is_stick` tinyint(3) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`is_paybill` tinyint(3) unsigned NOT NULL DEFAULT '0',
`self_audit_comment` tinyint(3) unsigned NOT NULL DEFAULT '0',
`delivery_extra` varchar(255) NOT NULL,
`elemeShopId` varchar(30) NOT NULL DEFAULT '0',
`eleme_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`meituan_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`openplateform_extra` varchar(1000) NOT NULL,
`meituanShopId` varchar(30) DEFAULT '0',
`data` text NOT NULL,
`position` tinyint(3) NOT NULL DEFAULT '1',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `title` (`title`),
KEY `is_recommend` (`is_recommend`),
KEY `cid` (`cid`),
KEY `status` (`status`),
KEY `label` (`label`),
KEY `displayorder` (`displayorder`),
KEY `is_stick` (`is_stick`),
KEY `agentid` (`agentid`),
KEY `elemeShopId` (`elemeShopId`),
KEY `meituanShopId` (`meituanShopId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_store_account` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`amount` decimal(10,2) NOT NULL DEFAULT '0.00',
`fee_limit` int(10) unsigned NOT NULL DEFAULT '0',
`fee_rate` varchar(10) NOT NULL DEFAULT '0',
`fee_min` int(10) unsigned NOT NULL DEFAULT '0',
`fee_max` int(10) unsigned NOT NULL DEFAULT '0',
`wechat` varchar(1000) NOT NULL,
`fee_takeout` varchar(500) NOT NULL,
`fee_instore` varchar(500) NOT NULL,
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`fee_paybill` varchar(500) NOT NULL,
`fee_eleme` varchar(500) NOT NULL,
`fee_meituan` varchar(500) NOT NULL,
`fee_selfDelivery` varchar(500) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_store_activity` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(255) NOT NULL,
`type` varchar(20) NOT NULL,
`data` varchar(1000) NOT NULL,
`starttime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `type` (`type`),
KEY `status` (`status`),
KEY `starttime` (`starttime`),
KEY `endtime` (`endtime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_store_category` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`thumb` varchar(255) NOT NULL,
`link` varchar(255) NOT NULL,
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`slide_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`slide` varchar(1500) NOT NULL,
`nav_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`nav` varchar(1500) NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`wxapp_link` varchar(255) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`),
KEY `status` (`status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_store_clerk` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`clerk_id` int(10) unsigned NOT NULL DEFAULT '0',
`role` varchar(20) NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`starttime|154|errander_deliveryerApp|9.0.0|20171010094422` int(10) unsigned NOT NULL DEFAULT '0',
`extra` varchar(500) NOT NULL,
`starttime|154|errander_deliveryerApp|9.4.1|20171121164734` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `clerk_id` (`clerk_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_store_current_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`trade_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1:订单入账, 2: 申请提现',
`extra` varchar(255) NOT NULL,
`fee` decimal(10,2) NOT NULL DEFAULT '0.00',
`amount` decimal(10,2) NOT NULL DEFAULT '0.00',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`remark` varchar(255) NOT NULL,
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `sid` (`sid`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_store_delivery_times` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`start` varchar(20) NOT NULL,
`end` varchar(20) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_store_deliveryer` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`deliveryer_id` int(10) unsigned NOT NULL DEFAULT '0',
`delivery_type` tinyint(3) unsigned NOT NULL DEFAULT '2',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
`work_status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`extra` varchar(500) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `agentid` (`agentid`),
KEY `work_status` (`work_status`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_store_favorite` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `uid_sid` (`uid`,`sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_store_getcash_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`trade_no` varchar(20) NOT NULL,
`get_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`take_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`final_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`account` varchar(500) NOT NULL,
`status` tinyint(3) unsigned NOT NULL DEFAULT '2' COMMENT '1:申请成功,2:申请中',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_store_members` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`openid` varchar(50) NOT NULL,
`first_order_time` int(10) unsigned NOT NULL DEFAULT '0',
`last_order_time` int(10) unsigned NOT NULL DEFAULT '0',
`success_num` int(10) unsigned DEFAULT '0',
`success_price` decimal(10,2) NOT NULL DEFAULT '0.00',
`cancel_num` int(10) unsigned NOT NULL DEFAULT '0',
`cancel_price` decimal(10,2) NOT NULL DEFAULT '0.00',
`is_sys` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '1:系统会员, 2:模块兼容会员',
`success_first_time` int(10) unsigned NOT NULL DEFAULT '0',
`success_last_time` int(10) unsigned NOT NULL DEFAULT '0',
`cancel_first_time` int(10) unsigned NOT NULL DEFAULT '0',
`cancel_last_time` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `sid` (`sid`),
KEY `uniacid` (`uniacid`),
KEY `first_order_time` (`success_first_time`),
KEY `last_order_time` (`success_last_time`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_store_settle_config` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`audit_status` tinyint(3) unsigned NOT NULL DEFAULT '2',
`mobile_verify_status` tinyint(3) unsigned NOT NULL DEFAULT '2',
`get_cash_fee_limit` int(10) unsigned NOT NULL DEFAULT '0',
`get_cash_fee_rate` varchar(10) NOT NULL,
`get_cash_fee_min` int(10) unsigned NOT NULL DEFAULT '0',
`get_cash_fee_max` int(10) unsigned NOT NULL DEFAULT '0',
`agreement` text,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_superredpacket` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) NOT NULL DEFAULT '0',
`name` varchar(255) NOT NULL,
`type` varchar(20) NOT NULL,
`data` text NOT NULL,
`grant_object` longtext NOT NULL,
`condition` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`status` tinyint(3) unsigned NOT NULL DEFAULT '0',
`starttime` int(10) unsigned NOT NULL DEFAULT '0',
`endtime` int(10) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `addtime` (`addtime`),
KEY `type` (`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_superredpacket_grant` (
`id` int(10) NOT NULL AUTO_INCREMENT,
`uniacid` int(10) NOT NULL DEFAULT '0',
`uid` int(10) unsigned NOT NULL DEFAULT '0',
`order_id` int(10) NOT NULL DEFAULT '0',
`activity_id` int(10) unsigned NOT NULL DEFAULT '0',
`packet_dosage` tinyint(3) unsigned NOT NULL DEFAULT '0',
`packet_total` tinyint(3) unsigned NOT NULL DEFAULT '0',
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `order_id` (`order_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_superredpacket_share` (
`id` int(10) NOT NULL AUTO_INCREMENT,
`uniacid` int(10) NOT NULL DEFAULT '0',
`activity_id` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(50) NOT NULL,
`discount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`condition` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
`grant_days_effect` tinyint(3) unsigned NOT NULL DEFAULT '0',
`use_days_limit` tinyint(3) unsigned NOT NULL DEFAULT '3',
`times_limit` text NOT NULL,
`category_limit` text NOT NULL,
`nums` int(10) unsigned NOT NULL DEFAULT '1',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_system_log` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`type` varchar(50) NOT NULL,
`title` varchar(50) NOT NULL,
`params` varchar(5000) NOT NULL,
`message` varchar(1000) NOT NULL,
`addtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `type` (`type`),
KEY `addtime` (`addtime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_tables` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`cid` int(10) unsigned NOT NULL DEFAULT '0',
`order_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '当前对应的订单id',
`guest_num` tinyint(3) unsigned DEFAULT '0',
`scan_num` int(10) unsigned NOT NULL DEFAULT '0',
`qrcode` varchar(500) NOT NULL,
`displayorder` tinyint(3) unsigned NOT NULL DEFAULT '0',
`status` tinyint(3) unsigned NOT NULL DEFAULT '1',
`createtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid_sid` (`uniacid`,`sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_tables_category` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`title` varchar(20) NOT NULL,
`limit_price` varchar(20) NOT NULL,
`reservation_price` varchar(20) NOT NULL,
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_tables_scan` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`sid` int(10) unsigned NOT NULL DEFAULT '0',
`table_id` int(10) unsigned NOT NULL DEFAULT '0',
`openid` varchar(50) NOT NULL,
`nickname` varchar(50) NOT NULL,
`avatar` varchar(255) NOT NULL,
`createtime` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `sid` (`sid`),
KEY `table_id` (`table_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tiny_wmall_text` (
`id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL DEFAULT '0',
`name` varchar(100) NOT NULL,
`value` text NOT NULL,
`agentid` int(10) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (`id`),
KEY `uniacid` (`uniacid`),
KEY `agentid` (`agentid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

");
